<a href="https://colab.research.google.com/github/k-washi/GoogleColab_ML/blob/master/pytorch_runtest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.cuda.is_available()

True

In [2]:
print(torch.__version__)

1.4.0


In [3]:
# 1 +  1/2 + 1/4 + 1/8 + ... = 2
x = torch.Tensor([0.])
y = torch.Tensor([1.])

for _ in range(50):
  x += y
  y /= 2

print(x)

tensor([2.])


In [0]:
#sequential nn
my_neuralnet = nn.Sequential(
    nn.Linear(3,2),
    nn.ReLU(),
    nn.Linear(2,1),
    nn.Sigmoid()

)

In [0]:
## NN module class
class MynuralNet(nn.Module):
  def __init__(self):
    #Initialize Operations for layers
    #super(NameOfClass, self).__init__()

    super(MynuralNet, self).__init__()
    self.operationOne = nn.Linear(3, 2)
    self.operationTwo = nn.Linear(2,1)
  
  def forward(self, x):
    #Describe the flow of data through the layers
    x = self.operationOne(x)
    x = F.relu(x)
    x = self.operationTwo(x)
    output = F.sigmoid(x)
    return output
  

In [0]:
my_network = MynuralNet()

In [10]:
#Pytorch tensors
first_order_tensor = torch.tensor([1, 2, 3])
print(first_order_tensor)
print(first_order_tensor[0])

print("-------------------")
second_order_tensor = torch.tensor([[11, 22, 33], [21, 22, 23]])
print(second_order_tensor)
print(second_order_tensor[0, 1])
print(second_order_tensor.size())

print(" random - - -----------")
random_tensor = torch.rand([4, 2])
print(random_tensor)
print("reshape-------")
print(random_tensor.view([2, 4]))

random_tensor = torch.rand([4,2,4])
print(random_tensor.view([2,4,-1]).size())
print(random_tensor.size())


tensor([1, 2, 3])
tensor(1)
-------------------
tensor([[11, 22, 33],
        [21, 22, 23]])
tensor(22)
torch.Size([2, 3])
 random - - -----------
tensor([[0.9372, 0.7773],
        [0.9491, 0.9337],
        [0.4798, 0.4298],
        [0.7613, 0.3845]])
reshape-------
tensor([[0.9372, 0.7773, 0.9491, 0.9337],
        [0.4798, 0.4298, 0.7613, 0.3845]])
torch.Size([2, 4, 4])
torch.Size([4, 2, 4])


In [17]:
#tensor operation
x = torch.tensor([5,3])
y = torch.tensor([3,2])
print(torch.add(x, y))
print(torch.sub(x,y))
print(torch.mul(x,y))
print(x + y)
print(torch.matmul(x, y))
print(x@y)
print(torch.sub(x, y))

x_f = torch.tensor([5, 3], dtype = torch.float32)
y_f = torch.tensor([3, 2], dtype = torch.float32)
print( x_f/y_f)

print(torch.FloatTensor([5, 3]))
#cast
print(x.type(torch.DoubleTensor))

tensor([8, 5])
tensor([2, 1])
tensor([15,  6])
tensor([8, 5])
tensor(21)
tensor(21)
tensor([2, 1])
tensor([1.6667, 1.5000])
tensor([5., 3.])
tensor([5., 3.], dtype=torch.float64)


In [0]:
#data import
from google.colab import files
#uploaded = files.uploaded()
#files.download({'filename})

In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [4]:
%cd "drive/My Drive/datasets/pytorch_test"

/content/drive/My Drive/datasets/pytorch_test


In [5]:
!ls 

admit_status.csv


In [8]:
import numpy as np
admit_data = np.genfromtxt('./admit_status.csv', delimiter = ',', skip_header=1)
print(admit_data)

[[  0.   380.     3.61   3.  ]
 [  1.   660.     3.67   3.  ]
 [  1.   800.     4.     1.  ]
 [  1.   640.     3.19   4.  ]
 [  0.   520.     2.93   4.  ]
 [  1.   760.     3.     2.  ]
 [  1.   560.     2.98   1.  ]
 [  0.   400.     3.08   2.  ]
 [  1.   540.     3.39   3.  ]]


In [15]:
admit_tensor = torch.from_numpy(admit_data)
print(admit_tensor)
print(admit_tensor.size())

tensor([[  0.0000, 380.0000,   3.6100,   3.0000],
        [  1.0000, 660.0000,   3.6700,   3.0000],
        [  1.0000, 800.0000,   4.0000,   1.0000],
        [  1.0000, 640.0000,   3.1900,   4.0000],
        [  0.0000, 520.0000,   2.9300,   4.0000],
        [  1.0000, 760.0000,   3.0000,   2.0000],
        [  1.0000, 560.0000,   2.9800,   1.0000],
        [  0.0000, 400.0000,   3.0800,   2.0000],
        [  1.0000, 540.0000,   3.3900,   3.0000]], dtype=torch.float64)
torch.Size([9, 4])


In [18]:
x_train = admit_tensor[:8, 1:]
y_train = admit_tensor[:8, 0]
x_test = admit_tensor[8:, 1:]
y_test = admit_tensor[8:, 0]
print(x_train, x_test)

tensor([[380.0000,   3.6100,   3.0000],
        [660.0000,   3.6700,   3.0000],
        [800.0000,   4.0000,   1.0000],
        [640.0000,   3.1900,   4.0000],
        [520.0000,   2.9300,   4.0000],
        [760.0000,   3.0000,   2.0000],
        [560.0000,   2.9800,   1.0000],
        [400.0000,   3.0800,   2.0000]], dtype=torch.float64) tensor([[540.0000,   3.3900,   3.0000]], dtype=torch.float64)


In [0]:
#binary cross-entropy loss
criterion = nn.BCELoss()
#SGD
optimizer = torch.optim.SGD(my_network.parameters(), lr=0.01)

In [0]:
for epoch in range(100):
  y_pred = my_network(x_train)

  loss_score = criterion(y_pred, y_train)
  print('epoch: ', epoch, 'loss: ', loss.item())

  #zero grad
  optimizer.zero_grad()

  loss_score.backward()

  optimizer.step()